package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

type roundTripFunc func(*http.Request) (*http.Response, error)

func (f roundTripFunc) RoundTrip(req *http.Request) (*http.Response, error) {
	return f(req)
}

func jsonResponse(statusCode int, body string) *http.Response {
	return &http.Response{
		StatusCode: statusCode,
		Header:     make(http.Header),
		Body:       io.NopCloser(strings.NewReader(body)),
	}
}

func TestSplitFrontMatterAndBody(t *testing.T) {
	input := []byte("---\ntitle: Test\n---\nBody here")
	fm, body := splitFrontMatterAndBody(input)
	// splitFrontMatterAndBody returns content[:end+8] where end is index of \n---\n in content[4:]
	// For "---\ntitle: Test\n---\nBody here", end=11, so fm = content[:19] = "---\ntitle: Test\n---"
	// and body = content[19:] = "\nBody here"
	if fm != "---\ntitle: Test\n---" {
		t.Fatalf("front matter = %q", fm)
	}
	if body != "\nBody here" {
		t.Fatalf("body = %q", body)
	}
}

func TestExtractFrontMatterField(t *testing.T) {
	input := []byte("---\ntitle: \"Hello World\"\ndescription: \"A test\"\ntags: [\"ai\"]\n---\nBody")

	if got := extractFrontMatterField(input, "title"); got != "Hello World" {
		t.Fatalf("title = %q, want %q", got, "Hello World")
	}
	if got := extractFrontMatterField(input, "description"); got != "A test" {
		t.Fatalf("description = %q, want %q", got, "A test")
	}
	if got := extractFrontMatterField(input, "missing"); got != "" {
		t.Fatalf("missing = %q, want empty", got)
	}
}

func TestContentHash(t *testing.T) {
	h1 := contentHash("hello")
	h2 := contentHash("hello")
	h3 := contentHash("world")

	if h1 != h2 {
		t.Fatal("same input should produce same hash")
	}
	if h1 == h3 {
		t.Fatal("different input should produce different hash")
	}
	if len(h1) != 32 {
		t.Fatalf("hash length = %d, want 32", len(h1))
	}
}

func TestInsertImageField(t *testing.T) {
	dir := t.TempDir()

	t.Run("insert after description", func(t *testing.T) {
		path := filepath.Join(dir, "test1.md")
		data := []byte("---\ntitle: \"Test\"\ndate: 2026-01-01\ndescription: \"A test post\"\ntags: [\"ai\"]\n---\nBody content here\n")
		os.WriteFile(path, data, 0644)

		err := insertImageField(path, data, "/images/test1-og.png")
		if err != nil {
			t.Fatal(err)
		}

		result, _ := os.ReadFile(path)
		if !strings.Contains(string(result), "images: [\"/images/test1-og.png\"]") {
			t.Fatalf("images field not inserted:\n%s", result)
		}
		if !strings.Contains(string(result), "Body content here") {
			t.Fatalf("body lost:\n%s", result)
		}
		// Verify order: images should come after description
		descIdx := strings.Index(string(result), "description:")
		imgIdx := strings.Index(string(result), "images:")
		if imgIdx < descIdx {
			t.Fatal("images field should come after description")
		}
	})

	t.Run("replace existing images field", func(t *testing.T) {
		path := filepath.Join(dir, "test2.md")
		data := []byte("---\ntitle: \"Test\"\nimages: [\"/images/old.png\"]\ndescription: \"A test\"\n---\nBody\n")
		os.WriteFile(path, data, 0644)

		err := insertImageField(path, data, "/images/test2-og.png")
		if err != nil {
			t.Fatal(err)
		}

		result, _ := os.ReadFile(path)
		if !strings.Contains(string(result), "images: [\"/images/test2-og.png\"]") {
			t.Fatalf("images field not replaced:\n%s", result)
		}
		if strings.Contains(string(result), "old.png") {
			t.Fatalf("old images field still present:\n%s", result)
		}
	})

	t.Run("no description field inserts before closing dashes", func(t *testing.T) {
		path := filepath.Join(dir, "test3.md")
		data := []byte("---\ntitle: \"Test\"\ntags: [\"go\"]\n---\nBody without description\n")
		os.WriteFile(path, data, 0644)

		err := insertImageField(path, data, "/images/test3-og.png")
		if err != nil {
			t.Fatal(err)
		}

		result, _ := os.ReadFile(path)
		if !strings.Contains(string(result), "images: [\"/images/test3-og.png\"]") {
			t.Fatalf("images field not inserted:\n%s", result)
		}
		if !strings.Contains(string(result), "Body without description") {
			t.Fatalf("body lost:\n%s", result)
		}
	})

	t.Run("appends AI disclaimer", func(t *testing.T) {
		path := filepath.Join(dir, "test4.md")
		data := []byte("---\ntitle: \"Test\"\ndescription: \"Desc\"\n---\nSome post body\n")
		os.WriteFile(path, data, 0644)

		err := insertImageField(path, data, "/images/test4-og.png")
		if err != nil {
			t.Fatal(err)
		}

		result, _ := os.ReadFile(path)
		if !strings.Contains(string(result), "cover image for this post was generated by AI") {
			t.Fatalf("disclaimer not appended:\n%s", result)
		}
	})

	t.Run("does not duplicate disclaimer", func(t *testing.T) {
		path := filepath.Join(dir, "test5.md")
		data := []byte("---\ntitle: \"Test\"\ndescription: \"Desc\"\nimages: [\"/images/test5-og.png\"]\n---\nBody\n\n*The cover image for this post was generated by AI.*\n")
		os.WriteFile(path, data, 0644)

		err := insertImageField(path, data, "/images/test5-og.png")
		if err != nil {
			t.Fatal(err)
		}

		result, _ := os.ReadFile(path)
		count := strings.Count(string(result), "cover image for this post was generated by AI")
		if count != 1 {
			t.Fatalf("disclaimer appears %d times, want 1:\n%s", count, result)
		}
	})
}

func TestGeneratePromptWithFallback(t *testing.T) {
	var modelsSeen []string

	originalFactory := httpClientFactory
	defer func() { httpClientFactory = originalFactory }()

	httpClientFactory = func() *http.Client {
		return &http.Client{
			Transport: roundTripFunc(func(r *http.Request) (*http.Response, error) {
				defer r.Body.Close()

				var req chatRequest
				if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
					t.Fatalf("decode request: %v", err)
				}

				modelsSeen = append(modelsSeen, req.Model)

				switch req.Model {
				case "model-a":
					return jsonResponse(http.StatusTooManyRequests, `{"error":{"message":"rate-limited"}}`), nil
				case "model-b":
					return jsonResponse(http.StatusOK, `{"choices":[{"message":{"content":"A dark network of glowing nodes connected by purple lines on black background"}}]}`), nil
				default:
					t.Fatalf("unexpected model %q", req.Model)
					return nil, nil
				}
			}),
		}
	}

	got := generatePrompt("https://example.invalid/v1/chat/completions", []string{"model-a", "model-b"}, "test-key", "Title: Test\nBody content")
	if got != "A dark network of glowing nodes connected by purple lines on black background" {
		t.Fatalf("got %q", got)
	}
	if len(modelsSeen) != 2 || modelsSeen[0] != "model-a" || modelsSeen[1] != "model-b" {
		t.Fatalf("models seen: %v", modelsSeen)
	}
}

func TestGenerateImageSuccess(t *testing.T) {
	originalFactory := httpClientFactory
	defer func() { httpClientFactory = originalFactory }()

	// Minimal valid PNG (1x1 pixel)
	pngData := []byte{
		0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, // PNG header
		0x00, 0x00, 0x00, 0x0D, 0x49, 0x48, 0x44, 0x52, // IHDR chunk
	}

	httpClientFactory = func() *http.Client {
		return &http.Client{
			Transport: roundTripFunc(func(r *http.Request) (*http.Response, error) {
				if r.Method == "POST" {
					defer r.Body.Close()
					var req falRequest
					if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
						t.Fatalf("decode fal request: %v", err)
					}
					if req.ImageSize.Width != 1200 || req.ImageSize.Height != 630 {
						t.Fatalf("image size = %dx%d, want 1200x630", req.ImageSize.Width, req.ImageSize.Height)
					}
					return jsonResponse(http.StatusOK, `{"images":[{"url":"https://example.invalid/image.png","content_type":"image/png"}]}`), nil
				}
				// GET request for image download
				return &http.Response{
					StatusCode: http.StatusOK,
					Header:     make(http.Header),
					Body:       io.NopCloser(strings.NewReader(string(pngData))),
				}, nil
			}),
		}
	}

	dir := t.TempDir()
	outputPath := filepath.Join(dir, "test-og.png")

	err := generateImage("https://example.invalid/fal", "test-key", "test prompt", outputPath)
	if err != nil {
		t.Fatal(err)
	}

	data, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatal(err)
	}
	if len(data) == 0 {
		t.Fatal("image file is empty")
	}
}

func TestContentHashSkipsUnchanged(t *testing.T) {
	dir := t.TempDir()
	contentDir := filepath.Join(dir, "content")
	imagesDir := filepath.Join(dir, "images")
	hashDir := filepath.Join(imagesDir, ".og-hashes")
	os.MkdirAll(contentDir, 0755)
	os.MkdirAll(hashDir, 0755)

	post := "---\ntitle: \"Test\"\ndescription: \"Desc\"\n---\nBody content\n"
	os.WriteFile(filepath.Join(contentDir, "test-post.md"), []byte(post), 0644)

	// Write hash matching the full prompt input (title + description + body)
	title := extractFrontMatterField([]byte(post), "title")
	description := extractFrontMatterField([]byte(post), "description")
	_, body := splitFrontMatterAndBody([]byte(post))
	hashInput := fmt.Sprintf("Title: %s\nDescription: %s\n\n%s", title, description, body)
	hash := contentHash(hashInput)
	os.WriteFile(filepath.Join(hashDir, "test-post.hash"), []byte(hash+"\n"), 0644)

	// The hash matches, so the post should be skipped.
	// We verify this indirectly: if it were NOT skipped, it would try to call the API
	// and fail (no HTTP client mock, no API keys).
	// This test just verifies the hash computation is consistent.
	existingHash, _ := os.ReadFile(filepath.Join(hashDir, "test-post.hash"))
	if strings.TrimSpace(string(existingHash)) != hash {
		t.Fatalf("hash mismatch: stored=%q, computed=%q", strings.TrimSpace(string(existingHash)), hash)
	}
}

func TestPostFilteringSkipsTranslations(t *testing.T) {
	// Verify the filtering logic
	skipLangs := []string{"de", "es"}
	tests := []struct {
		name string
		skip bool
	}{
		{"my-post.md", false},
		{"my-post.de.md", true},
		{"my-post.es.md", true},
		{"_index.md", true},
		{"_index.de.md", true},
		{"README.txt", true}, // not .md
	}

	for _, tt := range tests {
		shouldSkip := false
		if !strings.HasSuffix(tt.name, ".md") {
			shouldSkip = true
		} else if tt.name == "_index.md" || strings.HasPrefix(tt.name, "_index.") {
			shouldSkip = true
		} else {
			for _, lang := range skipLangs {
				if strings.HasSuffix(tt.name, "."+lang+".md") {
					shouldSkip = true
					break
				}
			}
		}

		if shouldSkip != tt.skip {
			t.Errorf("%s: skip=%v, want %v", tt.name, shouldSkip, tt.skip)
		}
	}
}

func TestShouldFallbackModel(t *testing.T) {
	if !shouldFallbackModel(http.StatusTooManyRequests, []byte(`{"error":"rate-limited"}`)) {
		t.Fatal("expected 429 to trigger fallback")
	}
	if shouldFallbackModel(http.StatusBadRequest, []byte(`{"error":"bad request"}`)) {
		t.Fatal("did not expect 400 to trigger fallback")
	}
	if !shouldFallbackModel(http.StatusInternalServerError, []byte(`error`)) {
		t.Fatal("expected 500 to trigger fallback")
	}
}

// projectRoot returns the repository root by stepping up from the test package directory.
func projectRoot() string {
	// Tests run with cwd = the package directory (cmd/generate-og-images),
	// so two levels up is the repository root.
	return filepath.Join("..", "..")
}

// readAllowedTags parses .github/allowed-tags.txt into a slice, skipping blank lines.
func readAllowedTags(t *testing.T) []string {
	t.Helper()
	path := filepath.Join(projectRoot(), ".github", "allowed-tags.txt")
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read allowed-tags.txt: %v", err)
	}
	var tags []string
	for _, line := range strings.Split(string(raw), "\n") {
		if line = strings.TrimSpace(line); line != "" {
			tags = append(tags, line)
		}
	}
	return tags
}

// TestAllowedTagsContainsNewTags verifies the two tags introduced by this PR are present.
func TestAllowedTagsContainsNewTags(t *testing.T) {
	tags := readAllowedTags(t)
	want := []string{"interpretability", "sparse-autoencoders"}
	tagSet := make(map[string]bool, len(tags))
	for _, tag := range tags {
		tagSet[tag] = true
	}
	for _, w := range want {
		if !tagSet[w] {
			t.Errorf("allowed-tags.txt missing expected tag %q", w)
		}
	}
}

// TestAllowedTagsIsSorted verifies every tag in the file is in ascending alphabetical order.
func TestAllowedTagsIsSorted(t *testing.T) {
	tags := readAllowedTags(t)
	for i := 1; i < len(tags); i++ {
		if tags[i] < tags[i-1] {
			t.Errorf("allowed-tags.txt is not sorted: %q appears after %q", tags[i], tags[i-1])
		}
	}
}

// TestAllowedTagsNoDuplicates verifies no tag appears more than once.
func TestAllowedTagsNoDuplicates(t *testing.T) {
	tags := readAllowedTags(t)
	seen := make(map[string]int)
	for _, tag := range tags {
		seen[tag]++
	}
	for tag, count := range seen {
		if count > 1 {
			t.Errorf("tag %q appears %d times in allowed-tags.txt", tag, count)
		}
	}
}

// TestAllowedTagsFormat verifies each tag is lowercase, non-empty, and contains only valid characters.
func TestAllowedTagsFormat(t *testing.T) {
	tags := readAllowedTags(t)
	for _, tag := range tags {
		if tag != strings.ToLower(tag) {
			t.Errorf("tag %q contains uppercase characters", tag)
		}
		for _, ch := range tag {
			if !((ch >= 'a' && ch <= 'z') || (ch >= '0' && ch <= '9') || ch == '-') {
				t.Errorf("tag %q contains invalid character %q", tag, ch)
			}
		}
	}
}

// parseTagList extracts tags from a front-matter tags field value like ["ai", "foo", "bar"].
func parseTagList(raw string) []string {
	raw = strings.TrimSpace(raw)
	raw = strings.TrimPrefix(raw, "[")
	raw = strings.TrimSuffix(raw, "]")
	var tags []string
	for _, part := range strings.Split(raw, ",") {
		tag := strings.TrimSpace(part)
		tag = strings.Trim(tag, `"`)
		tag = strings.TrimSpace(tag)
		if tag != "" {
			tags = append(tags, tag)
		}
	}
	return tags
}

func TestParseTagList(t *testing.T) {
	tests := []struct {
		input string
		want  []string
	}{
		{`["ai", "interpretability", "sparse-autoencoders"]`, []string{"ai", "interpretability", "sparse-autoencoders"}},
		{`["ai"]`, []string{"ai"}},
		{`[]`, nil},
		{``, nil},
	}
	for _, tt := range tests {
		got := parseTagList(tt.input)
		if len(got) != len(tt.want) {
			t.Errorf("parseTagList(%q) = %v, want %v", tt.input, got, tt.want)
			continue
		}
		for i := range got {
			if got[i] != tt.want[i] {
				t.Errorf("parseTagList(%q)[%d] = %q, want %q", tt.input, i, got[i], tt.want[i])
			}
		}
	}
}

// TestNewBlogPostHasRequiredFields verifies the new post has all required front matter fields.
func TestNewBlogPostHasRequiredFields(t *testing.T) {
	path := filepath.Join(projectRoot(), "content", "blog", "gemma3-sae-measurement-timing.md")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read blog post: %v", err)
	}
	required := []string{"title", "date", "description", "tags"}
	for _, field := range required {
		val := extractFrontMatterField(data, field)
		if val == "" {
			t.Errorf("front matter field %q is missing or empty", field)
		}
	}
}

// TestNewBlogPostTagsAreAllowed verifies every tag used in the new post exists in allowed-tags.txt.
func TestNewBlogPostTagsAreAllowed(t *testing.T) {
	path := filepath.Join(projectRoot(), "content", "blog", "gemma3-sae-measurement-timing.md")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read blog post: %v", err)
	}
	rawTags := extractFrontMatterField(data, "tags")
	postTags := parseTagList(rawTags)

	allowed := readAllowedTags(t)
	allowedSet := make(map[string]bool, len(allowed))
	for _, tag := range allowed {
		allowedSet[tag] = true
	}
	for _, tag := range postTags {
		if !allowedSet[tag] {
			t.Errorf("post uses tag %q which is not in allowed-tags.txt", tag)
		}
	}
}

// TestNewBlogPostUsesNewTags verifies the post specifically uses the two tags added in this PR.
func TestNewBlogPostUsesNewTags(t *testing.T) {
	path := filepath.Join(projectRoot(), "content", "blog", "gemma3-sae-measurement-timing.md")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read blog post: %v", err)
	}
	rawTags := extractFrontMatterField(data, "tags")
	postTags := parseTagList(rawTags)

	tagSet := make(map[string]bool, len(postTags))
	for _, tag := range postTags {
		tagSet[tag] = true
	}
	for _, want := range []string{"interpretability", "sparse-autoencoders"} {
		if !tagSet[want] {
			t.Errorf("expected new blog post to use tag %q, but it does not", want)
		}
	}
}

// TestNewBlogPostDateFormat verifies the date field follows YYYY-MM-DD format.
func TestNewBlogPostDateFormat(t *testing.T) {
	path := filepath.Join(projectRoot(), "content", "blog", "gemma3-sae-measurement-timing.md")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read blog post: %v", err)
	}
	date := extractFrontMatterField(data, "date")
	if date == "" {
		t.Fatal("date field is missing")
	}
	// Must be parseable as a date
	parts := strings.Split(date, "-")
	if len(parts) != 3 || len(parts[0]) != 4 || len(parts[1]) != 2 || len(parts[2]) != 2 {
		t.Errorf("date %q does not match YYYY-MM-DD format", date)
	}
}

// TestNewBlogPostBodyIsNonEmpty verifies the post body has actual content beyond the front matter.
func TestNewBlogPostBodyIsNonEmpty(t *testing.T) {
	path := filepath.Join(projectRoot(), "content", "blog", "gemma3-sae-measurement-timing.md")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read blog post: %v", err)
	}
	_, body := splitFrontMatterAndBody(data)
	if len(strings.TrimSpace(body)) == 0 {
		t.Fatal("blog post body is empty")
	}
}
func TestAppendDisclaimer(t *testing.T) {
	tests := []struct {
		name string
		body string
		want string
	}{
		{
			name: "empty body",
			body: "",
			want: aiImageDisclaimer,
		},
		{
			name: "body without disclaimer",
			body: "This is a post.",
			want: "This is a post." + aiImageDisclaimer,
		},
		{
			name: "body with trailing newlines",
			body: "This is a post.\n\n",
			want: "This is a post." + aiImageDisclaimer,
		},
		{
			name: "body already has disclaimer",
			body: "This is a post.\n\n*The cover image for this post was generated by AI.*\n",
			want: "This is a post.\n\n*The cover image for this post was generated by AI.*\n",
		},
		{
			name: "body contains partial disclaimer text",
			body: "Note that the cover image for this post was generated by AI.",
			want: "Note that the cover image for this post was generated by AI.",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := appendDisclaimer(tt.body); got != tt.want {
				t.Errorf("appendDisclaimer() = %q, want %q", got, tt.want)
			}
		})
	}
}
